
INSERT INTO USER (ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ACTIVE, REGISTER_DATE)
VALUES (1,'wd','willem','dragstra', 'wfdragstra@gmail.com', 'geheim', 1, '2019-08-12 09:50:45');
INSERT INTO USER (ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ACTIVE, REGISTER_DATE)
VALUES (2,'tc','tamara','coll', 'tamara@gmail.com', 'secreto', 1, '2019-08-12 09:50:45');

INSERT INTO COMPANY (ID, COMPANY_NAME, COMPANY_REF, DESCRIPTION, REGISTER_DATE)
VALUES (1,'Bitburger','Bitburger-ref-111','Bitte ein Bit','2021-04-12 09:50:45');
INSERT INTO COMPANY (ID, COMPANY_NAME, COMPANY_REF, DESCRIPTION, REGISTER_DATE)
VALUES (2,'Paulaner','Paulaner-ref-222','Das gute Bier allein...','2021-04-12 04:50:45');
INSERT INTO COMPANY (ID, COMPANY_NAME, COMPANY_REF, DESCRIPTION, REGISTER_DATE)
VALUES (3,'Radeberger','Radeberger-ref-333','Die Brauerei „Radeberger“ gewinnt auf jeden Fall!','2021-04-12 09:50:45');
INSERT INTO COMPANY (ID, COMPANY_NAME, COMPANY_REF, DESCRIPTION, REGISTER_DATE)
VALUES (4,'Beck','Beck-ref-444','Die Brauerei Beck & Co aus der Bremer Neustadt','2021-04-12 09:50:45');

INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (1, 'Premium Pils','Premium-Pils-ref-111', 1.20, 'HELLES', 'Deutschland', '2.5%', 0, 'Ein Gutes Bier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Bitburger-ref-111'));
INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (2, 'Bitburger Glutenfrei','Bitburger-Glutenfrei-ref-222', 2.35, 'PILS', 'Deutschland', '1.5%', 0, 'Ein Gesund Bier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Bitburger-ref-111'));
INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (3, 'PAULANER OKTOBERFEST BIER','Paulaner-Oktoberfest-ref-333', 1.70, 'STARKBIER', 'Deutschland', '3.8%', 0, 'Ein Oktoberfest Bier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Paulaner-ref-222'));
INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (4, 'Paulaner Weißbier','Paulaner-Weißbier-ref-444', 1.50, 'HELLES', 'Deutschland', '2.5%', 0, 'Ein Weißbier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Paulaner-ref-222'));
INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (5, 'Paulaner Alkoholfrei','Paulaner-Alkoholfrei-ref-555', 2.00, 'HELLES', 'Deutschland', '0%', 0, 'Ein Alkoholfreies Bier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Paulaner-ref-222'));
INSERT INTO PRODUCT (ID, NAME, PRODUCT_REF, PRICE, BEER_TYPE, NATIONALITY, GRADUATION, PROMOTION, DESCRIPTION, CREATION_DATE, COMPANY_ID)
VALUES (6, 'Radeberger Pilsner','Radeberger-Pilsner-ref-777', 0.95, 'PILS', 'Deutschland', '1.5%', 0, 'Ein Gutes Bier', '2019-08-12 09:50:45', (SELECT ID FROM COMPANY WHERE COMPANY_REF='Radeberger-ref-333'));

INSERT INTO USER_COMPANY (USER_ID, COMPANY_ID)
VALUES ((SELECT ID FROM USER WHERE USERNAME='wd'), (SELECT ID FROM COMPANY WHERE COMPANY_REF='Bitburger-ref-111'));

INSERT INTO USER_COMPANY (USER_ID, COMPANY_ID)
VALUES ((SELECT ID FROM USER WHERE USERNAME='wd'), (SELECT ID FROM COMPANY WHERE COMPANY_REF='Paulaner-ref-222'));

INSERT INTO USER_COMPANY (USER_ID, COMPANY_ID)
VALUES ((SELECT ID FROM USER WHERE USERNAME='tc'), (SELECT ID FROM COMPANY WHERE COMPANY_REF='Bitburger-ref-111'));